---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  type: NodePort
  selector:
    app: elasticsearch-single
  ports:
  - name: http
    port: 9200
    nodePort: 31290
    protocol: TCP
  - name: tcp
    port: 9300
    protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elasticsearch-single
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: elasticsearch-single
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
          {
              "name": "init",
              "image": "busybox:latest",
              "command": [ "sh", "-c", "chown 1005:1005 /opt/elasticsearch/data /opt/elasticsearch/logs" ],
              "volumeMounts": [
                { "name": "data", "mountPath": "/opt/elasticsearch/data" },
                { "name": "logs", "mountPath": "/opt/elasticsearch/logs" }
              ],
              "imagePullPolicy": "IfNotPresent"
            }
          ]'
    spec:
      containers:
      - name: elasticsearch
        securityContext:
          privileged: true
          capabilities:
            add:
              - IPC_LOCK
              - SYS_RESOURCE
        imagePullPolicy: Always
        image: henryrao/elasticsearch:2.3.3
        ports:
        - containerPort: 9200
        - containerPort: 9300
        env:
        - name: ES_HEAP_SIZE
          value: 2g
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        args:
        - "run.sh"
        - "elasticsearch"
        - "-Dcluster.name=myesdb"
        - "-Dhttp.cors.enabled=true"
        - "-Dbootstrap.mlockall=true"
        - "-Dnetwork.host=0.0.0.0"
        volumeMounts:
        - name: data
          mountPath: /opt/elasticsearch/data
        - name: logs
          mountPath: /opt/elasticsearch/logs
      volumes:
      - name: data
        emptyDir: {}
      - name: logs
        emptyDir: {}
