---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    component: elasticsearch
    role: client
spec:
  type: NodePort
  selector:
    app: elasticsearch
    elasticsearch: client
  ports:
  - name: http
    port: 9200
    protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: es-client
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: elasticsearch
        elasticsearch: client
    spec:
      containers:
      - name: es-client
        securityContext:
          privileged: true
          capabilities:
            add:
              - IPC_LOCK
              - SYS_RESOURCE
        imagePullPolicy: Always
        image: henryrao/elasticsearch:2.3.3
        ports:
        - containerPort: 9300
        env:
        - name: ES_HEAP_SIZE
          value: 128m
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        args:
        - "run.sh"
        - "elasticsearch"
        - "-Dcluster.name=myesdb"
        - "-Dhttp.cors.enabled=true"
        - "-Dhttp.cors.allow-origin=*"
        - "-Dbootstrap.mlockall=true"
        - "-Dnetwork.host=0.0.0.0"
        - "-Dnode.master=false"
        - "-Dnode.data=false"
        - "-Dhttp.enabled=true"
        - "-Ddiscovery.zen.ping.unicast.hosts=elasticsearch-discovery.default.svc.cluster.local"
        volumeMounts:
        - name: data
          mountPath: /opt/elasticsearch/data
        - name: logs
          mountPath: /opt/elasticsearch/logs
      volumes:
      - name: data
        emptyDir: {}
      - name: logs
        emptyDir: {}
