---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-discovery
  labels:
    app: elasticsearch
spec:
  selector:
    elasticsearch: master
  ports:
  - name: transport
    port: 9300
    protocol: TCP
