---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-discovery" .Values.service.name | trunc 63 }}
  labels:
{{ include "labels" . | indent 4 }}
spec:
  selector:
{{ include "labels.master" . | indent 4 }}
  ports:
  - name: transport
    port: 9300
    protocol: TCP
