---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ printf "%s-client" .Values.service.name | trunc 63 }}
  labels:
{{ include "labels" . | indent 4 }}      
spec:
  replicas: {{ .Values.replicaCount.client }}
  template:
    metadata:
      labels:
{{ include "labels.client" . | indent 8 }}      
    spec:
      containers:
      - name: es-client
        securityContext:
          privileged: true
          capabilities:
            add:
              - IPC_LOCK
              - SYS_RESOURCE
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 9300
        env:
        - name: ES_HEAP_SIZE
          value: {{ .Values.heapSize.client }}
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        args:
        - "run.sh"
        - "elasticsearch"
        - {{ printf "-Dcluster.name=%s" .Values.config.cluster.name | quote }} 
        - "-Dhttp.cors.enabled=true"
        - "-Dhttp.cors.allow-origin=*"
        - "-Dnode.master=false"
        - "-Dnode.data=false"
        - "-Dhttp.enabled=true"
        - {{ printf "-Ddiscovery.zen.ping.unicast.hosts=%s-discovery.default.svc.cluster.local" .Values.service.name | quote }}
