---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ printf "%s-master" .Values.service.name | trunc 63 }} 
  labels:
{{ include "labels" . | indent 4 }}      
spec:
  replicas: {{ .Values.replicaCount.master }}
  template:
    metadata:
      labels:
{{ include "labels.master" . | indent 8 }}
    spec:
      containers:
      - name: es-master
        securityContext:
          privileged: true
          capabilities:
            add:
              - IPC_LOCK
              - SYS_RESOURCE
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 9300
        env:
        - name: ES_HEAP_SIZE
          value: {{ .Values.heapSize.master }}
        args:
        - "run.sh"
        - "elasticsearch"
        - {{ printf "-Dcluster.name=%s" .Values.config.cluster.name | quote }}
        - "-Dnode.master=true"
        - "-Dnode.data=false"
        - "-Dhttp.enabled=false"
        - {{ printf "-Ddiscovery.zen.ping.unicast.hosts=%s-discovery.default.svc.cluster.local" .Values.service.name | quote }}
        volumeMounts:
        - name: storage
          mountPath: {{ .Values.volumes.data.mountPath }}
      volumes:
      - name: storage
        emptyDir: {}
