---
apiVersion: v1
kind: Service
metadata:
  name: {{ required "A valid service.name is required" .Values.service.name }}
  labels:
{{ include "labels" . | indent 4 }}
spec:
  type: NodePort
  selector:
{{ include "labels.client" . | indent 4 }}    
  ports:
  - name: http
    port: 9200
    protocol: TCP
